### ISSUE TITLE
order by custom field is written to content type yml as id

### ISSUE THREAD

**Issue by tpreusse** [locomotivecms/wagon#111]
if you order a content type by a custom field via the admin interface and then do a pull the id of the custom field is written to the yml file of the content type.

example

``` yml

---
name: Articles
description: some articles
slug: magazine
label_field_name: title
order_by: 512b647bc086453dc300000e
```

this breaks when pushing between multiple env with different field ids
