### ISSUE TITLE
not sure how to push to engine running locally

### ISSUE THREAD

**Issue by urbanistica** [locomotivecms/wagon#142]
deploy.yml says

```
development:
  host: 0.0.0.0:8080
  email: myemail@gmail.com
  password: password
  # api_key: <your api key here>
```

calling `bundle exec wagon push development` gets me

_unable to get an API token: bad URI(is not URI?): 0.0.0.0:8080/locomotive/api_

Where's the API token supposed to come from? I have this pushing to a heroku-mounted engine and all's good. But don't I want to have it also pushing to a local engine?
