### ISSUE TITLE
entries of content types with required belongs_to can't be pushed

### ISSUE THREAD

**Issue by tpreusse** [locomotivecms/wagon#163]
**wagon push**
```
* Pushing ContentEntries
  de
    creating events / a-party      location => leer
```

**app/content_types/events.yml**
```
- location:
    label: location
    type: belongs_to
    unique: false
    localized: false
    class_name: location_page
    ui_enabled: true
```

since wagon first pushed the entries without the relationship this fails (engine rejects invalid entry). don't know what the best solution would be
