### ISSUE TITLE
how to link images in css

### ISSUE THREAD

**Issue by onnimonni** [locomotivecms/wagon#181]
Hello!

I'm having problems with linking background-images in the css files. It's easy to do with liquid helpers in the html template but I can't do similar thing in css.

`style.css:`

``` css
.theme-default .nivoSlider {
    background:#fff url(loading.gif) no-repeat 50% 50%;
}
```

How to make this work with locomotive?
