### ISSUE TITLE
Wagon push fails when pushing a wagon site to a multi-site locomotive engine

### ISSUE THREAD

**Issue by nicsunboy** [locomotivecms/wagon#234]
Hi,
I always got errors when i pushed a wagon to a multi-site locomotive engines.I tries 2 different settings of deploy.yml and site.yml
Try 1 
deploy.yml:
```
 development:
   host: fg2_wagon.me.dev:8080
   email: xxxx@xxxxx.com
   password: <password>
   #api_key: .....
staging:
   host: fg2_wagon.me.dev:8080
   email: xxxx@xxxxx.com
   password: <password>
   #api_key: .....
production:
   host: fg2_wagon.me.dev:8080
   email: xxxx@xxxxx.com
   password: <password>
   #api_key: .....
```
site.yml:
```
name: "fg2_wagon"
subdomain: fg2_wagon
locales: [en]
seo_title: fg2_wagon
meta_keywords: "some meta keywords"
meta_description: "some meta description"
```
under Try 1 setting, bundle exec wagon push development -v ,which return

``` bash
tsikun@kali:~/fg2_wagon$ bundle exec wagon push development -v
unable to get an API token: bad URI(is not URI?): fg2_wagon.me.dev:8080/locomotive/api
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/locomotivecms_mounter-1.5.2/lib/locomotive/mounter/writer/api.rb:36:in `rescue in prepare'
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/locomotivecms_mounter-1.5.2/lib/locomotive/mounter/writer/api.rb:32:in `prepare'
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/locomotivecms_mounter-1.5.2/lib/locomotive/mounter/writer/runner.rb:27:in `run!'
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/locomotivecms_wagon-1.5.3/lib/locomotive/wagon.rb:171:in `push'
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/locomotivecms_wagon-1.5.3/lib/locomotive/wagon/cli.rb:311:in `push'
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
```

Try 2
deploy.yml:
```
 development:
   host: me.dev:8080
   email: xxxx@xxxxx.com
   password: <password>
   #api_key: .....
staging:
   host: me.dev:8080
   email: xxxx@xxxxx.com
   password: <password>
   #api_key: .....
production:
   host: me.dev:8080
   email: xxxx@xxxxx.com
   password: <password>
   #api_key: .....
```
site.yml:
same as Try 1

under Try 2 setting, bundle exec wagon push development -v ,which return

``` bash
* Pushing Site
  en
    creating fg2_wagon..........................................................[done]
* Pushing Snippets
No site found
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/locomotivecms_mounter-1.5.2/lib/locomotive/mounter/writer/api/base.rb:54:in `rescue in get'
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/locomotivecms_mounter-1.5.2/lib/locomotive/mounter/writer/api/base.rb:51:in `get'
	/home/tsikun/.rvm/gems/ruby-2.0.0-p598@rails3.2/gems/locomotivecms_mounter-1.5.2/lib/locomotive/mounter/writer/api/snippets_writer.rb:16:in `prepare'

```
/etc/hosts:
127.0.0.1 	me.dev
127.0.0.1 	site_a.me.dev
127.0.0.1 	site_b.me.dev
127.0.0.1 	fg2_wagon.me.dev

what caused issues happen? I configured wrong or  wagon didn't support multi-site pushing.
thanks for your reply!
