### ISSUE TITLE
Undefined method `label_field_name' for nil:NilClass

### ISSUE THREAD

**Issue by cke4** [locomotivecms/wagon#243]
I have products.yml file with data like this:
```yaml
    - "object 1":
        _slug: obj1
        title: "object 1"
        category: cat1
        max: 500
    - "object 2":
        _slug: obj2
        title: "object 2"
        category: cat1
        max: 550
    - "object 3":
        _slug: obj3
        title: "object 3"
        category: cat1
        max: 1500
    - "object 4":
        _slug: obj4
        title: "object 4"
        category: cat2
        max: 600
```
I try to create new content entry by code in *app/models/locomotive/content_entry.rb*:
```ruby
def self.import (values)
    ce = Locomotive::ContentEntry.create(values)
end
```
where values - result of parsing products.yml by this code in *app/controllers/yaml_controller.rb*:
```ruby
data = YAML.load_file('products.yml')
data.each do |key, values|
     Locomotive::ContentEntry.import(key)
end
```
But when i try to start my code, there is a mistake.

LocomotiveCMS. Undefined method `label_field_name' for nil:NilClass

I don't understand what i do incorrectly. So my question is the same as https://github.com/locomotivecms/wagon/issues/204 I have a lot of data and API can't upload it correctly. So i need to upload data inside of engine. 
Please help. Thanks!
