### ISSUE TITLE
`with_scope` doesn't work with `many_to_many` relationship field type for wagon 2.0.0.rc4

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#270]
![zaznaczenie_016](https://cloud.githubusercontent.com/assets/2798350/11425612/5e0715b8-9456-11e5-90d2-a81fe239d9be.png)
Let's create new project based on example from docs [LocomotiveCMS Guide - many_to_many](https://github.com/geraudmathe/Locomotive-fundamentals#many-to-many).

1. Make sure you use wagon `2.0.0.rc4`
    ```
    $ wagon version
    2.0.0.rc4
    ```

2. Create new Wagon site
    ```
    mkdir -p ~/Sites/Wagon
    cd ~/Sites/Wagon
    wagon init MyPortfolio -t bootstrap
    cd MyPortfolio
    bundle install
    ```

3. Ensure Gemfile uses correct wagon gem:
    ```
    $ cat Gemfile
    source 'https://rubygems.org'

    gem 'locomotivecms_wagon', '~> 2.0.0.rc4'

    # gem 'guard-livereload', '~> 2.5.1'

    group :development do
      # Mac OS X
      gem 'rb-fsevent', '~> 0.9.1', require: 'rb-fsevent' if RUBY_PLATFORM.include?('darwin')

      # Unix
      gem 'therubyracer', require: 'v8', platforms: :ruby unless RUBY_PLATFORM.include?('darwin')

      gem 'rb-inotify', '~> 0.9', require: 'rb-inotify' if RUBY_PLATFORM.include?('linux')

      # Windows
      gem 'wdm', '~> 0.1.1', require: 'wdm' if RUBY_PLATFORM =~ /mswin|mingw/i
    end

    group :misc do
      # Add your extra gems here
      # gem 'susy', require: 'susy'
      # gem 'bourbon', require: 'bourbon'
    end
    ```

4. Create `Tags` content_type:
    ```
    bundle exec wagon generate content_type tags text:string books:many_to_many
    ```

5. Create `Books` content_type:
    ```
    bundle exec wagon generate content_type books title:string tags:many_to_many
    ```

6. Edit `app/content_types/tags.yml`
    ```
    name: Tags
    slug: tags
    description: A description of the content type for the editors
    label_field_name: text
    order_by: manually
    fields: 
    - text:
        label: Text
        type: string
        required: true
        hint: A name
        localized: false
    - books:
        label: Books
        type: many_to_many
        required: false
        hint: Books related to this tag
        localized: false
        class_name: books
        inverse_of: tags
        ui_enabled: true
    ```

7. Edit `app/content_types/books.yml`
    ```
    name: Books
    slug: books
    description: A description of the content type for the editors
    label_field_name: title
    order_by: manually
    fields:
    - title:
        label: Title
        type: string
        required: true
        hint: A title
        localized: false
    - tags:
        label: Tags
        type: many_to_many
        required: false
        hint: Tags related to this book
        localized: false
        class_name: tags
        inverse_of: books
        ui_enabled: true
    ```

8. Prepare `data/tags.yml` data:
    ```
    - "Tag 1":
        books: null
    - "Tag 2":
        books: null
    - "Tag 3":
        books: null
    ```

9. Prepare `data/books.yml` data:
    ```
    - "Book A":
        tags: ['tag-1']
    - "Book B":
        tags: ['tag-2']
    - "Book C":
        tags: ['tag-3']
    - "Book D":
        tags: ['tag-1', 'tag-2']
    - "Book E":
        tags: ['tag-1', 'tag-3']
    - "Book F":
        tags: ['tag-2', 'tag-3']
    - "Book G":
        tags: ['tag-1', 'tag-2', 'tag-3']
```

10. Build the page listing the books

    ```
    bundle exec wagon generate page books
    ```

11. Open the `app/views/pages/books.liquid` page in your code editor and replace the liquid code below the second "---":
    ```
    {% extends 'layouts/simple' %}
    
    {% block content/main, short_name: true %}
    
    {% editable_model books %}
    <div class="row">
      <div class="col-sm-6">
        <h3>1. All books ({{ contents.books.size }})</h3>
        {% for book in contents.books %}
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">{{ book.title }} ({{ book._slug }})</h4>
            <p><strong>Tags:</strong></p>
            <ul>
              {% for tag in book.tags %}
                <li>{{ tag.text }} ({{ tag._slug }})</li>
              {% endfor %}
            </ul>
          </div>
        </div>
        {% endfor %}
      </div>
    
      <div class="col-sm-6">
      {% if true %}
        {% assign tag = contents.tags.first %}
        {% with_scope tags.in: tag %}
          {% assign my_books = contents.books.all %}
        {% endwith_scope %}
      {% endif %}
    
        <h3>2. Filtered book for tag "{{ tag.text}} / {{ tag._slug }}" ({{ my_books.size }})</h3>
        {% for book in my_books %}
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">{{ book.title }}</h4>
            <p><strong>Tags:</strong></p>
            <ul>
              {% for tag in book.tags %}
                <li>{{ tag.text }}</li>
              {% endfor %}
            </ul>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endeditable_model %}
    
    {% endblock %}
    ```

11. Launch the Wagon preview server
    ```
    bundle exec wagon serve  -v
    ```

12. Open internet browser with address `localhost:3333/books`
    You can see two lists:
    - first one on the left side: all book with assigned tags
    - second one on the right side: filtered books by first tag `Tag 1` (empty list)
 
WHATS WRONG
 - second list on the right side is empty
 - changing `tags.in` into `tags` doesn't help
 
IT SHOULD BE
 - second list on the right side should have 4 items instead of 0
 - if we change `{% assign tag = contents.tags.first %}` into `{% assign tag = contents.tags.all %}` it should return 7 books
