### ISSUE TITLE
`with_scope` doesn't work with `belong_to` relationship field type for wagon 2.0.0.rc4

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#275]
Let's create new project based two content_types: `books` and `categories`.
Every book belongs to one category.
One category has many books.

1. Make sure you use wagon `2.0.0.rc4`
    ```
    $ wagon version
    2.0.0.rc4
    ```

2. Create new Wagon site
    ```
    mkdir -p ~/Sites/Wagon
    cd ~/Sites/Wagon
    wagon init Library -t bootstrap
    cd Library
    bundle install
    ```

3. Ensure Gemfile uses correct wagon gem:
    ```
    $ cat Gemfile
    source 'https://rubygems.org'

    gem 'locomotivecms_wagon', '~> 2.0.0.rc4'

    # gem 'guard-livereload', '~> 2.5.1'

    group :development do
      # Mac OS X
      gem 'rb-fsevent', '~> 0.9.1', require: 'rb-fsevent' if RUBY_PLATFORM.include?('darwin')

      # Unix
      gem 'therubyracer', require: 'v8', platforms: :ruby unless RUBY_PLATFORM.include?('darwin')

      gem 'rb-inotify', '~> 0.9', require: 'rb-inotify' if RUBY_PLATFORM.include?('linux')

      # Windows
      gem 'wdm', '~> 0.1.1', require: 'wdm' if RUBY_PLATFORM =~ /mswin|mingw/i
    end

    group :misc do
      # Add your extra gems here
      # gem 'susy', require: 'susy'
      # gem 'bourbon', require: 'bourbon'
    end
    ```

4. Create `Categories` content_type:
    ```
    bundle exec wagon generate content_type categories name:string
    ```

5. Create `Books` content_type:
    ```
    bundle exec wagon generate content_type books title:string 
    bundle exec wagon generate relationship books belongs_to categories
    ```

6. Edit `app/content_types/categories.yml` (just add `required: false` and `localized: false` lines for the second field)
    ```
    name: Categories
    slug: categories
    description: A description of the content type for the editors
    label_field_name: name
    order_by: manually
    fields: 
    - name:
        label: Name
        hint: A name
        type: string
        required: true
        localized: false
    - books:
        label: Books
        hint: Books related to this category
        type: has_many
        required: false
        localized: false
        class_name: books
        inverse_of: category
        ui_enabled: true
    ```

7. Edit `app/content_types/books.yml`
    ```
    name: Books
    slug: books
    description: A description of the content type for the editors
    label_field_name: title
    order_by: manually
    fields:
    - title:
        label: Title
        type: string
        required: true
        hint: A title
        localized: false
    - category:
        label: Category
        hint: Category related to this book
        type: belong_to
        required: false
        localized: false
        class_name: categories
    ```

8. Prepare `data/categories.yml` data:
    ```
    - "Category 1":
        books: null
    - "Category 2":
        books: null
    - "Category 3":
        books: null
    ```

9. Prepare `data/books.yml` data:
    ```
    - "Book A":
        category: 'category-1'
    - "Book B":
        category: 'category-1'
    - "Book C":
        category: 'category-2'
    - "Book D":
        category: 'category-2'
    - "Book E":
        category: 'category-3'
    - "Book F":
        category: 'category-3'
    - "Book G":
        category: 'category-3'
    ```

10. Build the page listing the books

    ```
    bundle exec wagon generate page books
    ```

11. Open the `app/views/pages/books.liquid` page in your code editor and replace the liquid code below the second "---":
    ```
    {% extends 'layouts/simple' %}

    {% block content/main, short_name: true %}

    {% editable_model books %}
    <div class="row">
      <div class="col-sm-3">
        <h3>1. All books ({{ contents.books.size }})</h3>
        {% for book in contents.books %}
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">{{ book.title }} ({{ book._slug }})</h4>
            <p>
              <strong>Category:</strong> {{ category.name }} ({{ category._slug }})
            </p>
          </div>
        </div>
        {% endfor %}
      </div>

      <div class="col-sm-9">
      {% if false %}
        {% assign category = contents.categories.first %}
        {% with_scope category: category %}
          {% assign my_books = contents.books.all %}
        {% endwith_scope %}
      {% else %}
        {% assign category = contents.categories.first %}
        {% assign category2 = contents.categories.last %}
        {% with_scope category.in: [category, category2] %}
          {% assign my_books = contents.books.all %}
        {% endwith_scope %}
      {% endif %}

        <h3>2. Filtered book for categories: "{{ category.name}} ({{ category._slug }}), {{ category2.name }} ({{ category2._slug }})" ({{ my_books.size }})</h3>
        {% for book in my_books %}
        <div class="media">
          <div class="media-body">
            <h4 class="media-heading">{{ book.title }}</h4>
            <p>
              <strong>Category:</strong> {{ category.name }} ({{ category._slug }})
            </p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endeditable_model %}

    {% endblock %}
    ```

11. Launch the Wagon preview server
    ```
    bundle exec wagon serve  -v
    ```

12. Open internet browser with address `localhost:3333/books`
    You can see two lists:
    - first one on the left side: all book with assigned categories
    - second one on the right side: filtered books by two categories `Category 1` & `Category 3` (empty list)
    - if you change condition `{% if false %}` into `{% if true %}` you get two items
 
WHATS WRONG
 - second list on the right side is empty
 - changing `with_scope category.in` into `with_scope category` doesn't help
 - changing `with_scope category.in: [category, category2]` into `with_scope category.in: contents.categories.all` doesn't help
 - `with_scope` works only for one category.
 
IT SHOULD BE
 - second list on the right side should have 5 items instead of 0
 - if we change `with_scope category.in: [category, category2]` into `with_scope category.in: contents.categories.all` it should return 7 books (all items)
 - `with_scope` should work with many categories.

![zaznaczenie_020](https://cloud.githubusercontent.com/assets/2798350/11444185/cba96922-9523-11e5-9ac1-2cbcf1d85d7c.png)
