### ISSUE TITLE
Clone to local site results in Malformed data YAML

### ISSUE THREAD

**Issue by hblackett** [locomotivecms/wagon#292]
When I sync from production to local site it results in the following error:

`Malformed YAML in this file /.../Sites/Wagon/.../data/years.yml, error: undefined method 'to_sym' for 2014:Fixnum`

The data/years.yml file looks like this:

```
- 2014:
    _slug: '2014'
    name: 2014
    projects:
    - residency-works
```

Didier helpfully suggested a fix by changing the years.yml file to:

```
- "2014":
    _slug: '2014'
    name: 2014
    projects:
    - residency-works
```

Is there a way to avoid having to manually update the year.yml file after each sync?
