### ISSUE TITLE
site.metafields iteration has different order

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#296]
1. File `config/metafields_schema.yml` has:

  ```
hours:
  label: 'Hours Opening'
  position: 2
  fields:
    line1::
      hint: "Day 1"
      type: string
    line2::
      hint: "Day 2"
      type: string
    line3::
      hint: "Day 3"
      type: string
    line4::
      hint: "Day 4"
      type: string
    line5::
      hint: "Day 5"
      type: string
  ```
1. File `config/site.yml` includes following data:

  ```
metafields:
  hours:
    line1: 'Mo,06:00-22:00'
    line2: 'Tu,06:00-23:00'
    line3: 'We,06:00-23:00'
    line4: 'Th,07:30-23:30'
    line5: 'Fr,07:30-21:30'
  ```
1. According example from [Documentatrion "Use metafields in Liquid"](https://locomotive-v3.readme.io/docs/site-metafields#section-examples) we should be able to iterate defined hours like this:

```
<ul>
  {% for metafield in site.metafields.hours %}
  <li>{{ metafield.value }}</li>
  {% endfor %}
</ul>
```

WHAT'S WRONG
1. `site.metafields iteration` has different order:
```
Fr 07:30-21:30 
We 06:00-23:00 
Mo 06:00-22:00
Th 07:30-23:30
Tu 06:00-23:00
```

Why?

INFO
1. Tested only with the Wagon

P.S. @did, I love metafields except the issue :-) Very nice feature. Many my earlier problems has gone.
