### ISSUE TITLE
Undefined method `to_sym' when pushing ContentEntries after 1.5.8 -> 2.0.1 upgrade

### ISSUE THREAD

**Issue by dradford** [locomotivecms/wagon#299]
Hi there,

I'm experiencing the following error message when trying to push content to station.locomotive.works. I've just upgraded my wagon gem from 1.5.8 to 2.0.1 and I can push all resources fine, however when I include the -d flag it gives me the following error:

```undefined method `to_sym' for ["_position", "asc"]:Array```

Error appears to occur on this line:

```gems/locomotivecms_steam-1.0.1/lib/locomotive/steam/entities/content_type_field.rb:30:in `order_by'```

Cheers,
Damien

**Comment by did** [comment]
hi @dradford! what's in your content type yaml file?

**Comment by dradford** [comment]
Found this in one of my content type yaml files, not sure how order_by and asc ended up in the "jobs" field:

```
---
name: Departments
description: Departments used for job positions
slug: departments
label_field_name: name
order_by: manually
order_direction: asc
fields:
- name:
    label: Name
    type: string
    required: true
    unique: false
    localized: false
- jobs:
    label: Jobs
    type: has_many
    required: false
    unique: false
    localized: false
    class_name: jobs
    inverse_of: department
    order_by:
    - _position
    - asc
```

**Comment by did** [comment]
thanks @dradford. Will look into it.

**Comment by did** [comment]
Could you try this instead:
````
- jobs:
    label: Jobs
    type: has_many
    required: false
    unique: false
    localized: false
    class_name: jobs
    inverse_of: department
    order_by: **"_position asc"**
````
That should work!
