### ISSUE TITLE
allow scss for fonts/all

### ISSUE THREAD

**Issue by tpreusse** [locomotivecms/wagon#32]
``` SCSS
@mixin bulletproof-font-face($name, $file-name) {
  @font-face {
    font-family: $name;
    src: url("#{$file-name}.eot");
    src: local('?'),
      url("#{$file-name}.woff") format("woff"),
      url("#{$file-name}.otf") format("opentype"),
      url("#{$file-name}.ttf") format("truetype");
    }
  @media screen and (max-device-width: 480px) {
    @font-face {
      font-family: $name;
      src: url("#{$file-name}.woff") format("woff"),
      url("#{$file-name}.otf") format("opentype"),
      url("#{$file-name}.ttf") format("truetype");
  }}
}
```

Source: http://paulirish.com/2009/bulletproof-font-face-implementation-syntax/

would be nice to use to be able to use something like that without manual scss to css conversion.
