### ISSUE TITLE
Missing password field when using wagon backup

### ISSUE THREAD

**Issue by fabioskap** [locomotivecms/wagon#357]
Hi @did 

**Wagon version** : 2.3.1
**Engine version** : 3.3.0

I created a content type for users, with these fields:
```yaml
fields:
- name:
    label: Name
    type: string
    required: true
    localized: false

- email: 
    label: Email
    type: email
    required: true
    unique: true
    localized: false

- password: 
    label: Password 
    type: password
    required: true
    localized: false
```
The authentication works, but when I use ```wagon backup``` the content entries look like this (password field is missing):

```yaml
- example@mail.com:
    _slug: example-at-mail-dot-com
    name: 'exampleName1'
    email: example@mail.com

- example2@mail2.com:
    _slug: example2-at-mail2-dot-com
    name: 'exampleName2'
    email: example2@mail2.com
```

Is this intended or it is a bug?
