### ISSUE TITLE
wagon push: multi locale content entries fails

### ISSUE THREAD

**Issue by tpreusse** [locomotivecms/wagon#38]
Locomotive::Mounter::Models::ContentEntry#set_slug
fails with `undefined method 'permalink!'` when used via `be wagon push ENV`

``` Ruby
# Sets the slug of the instance by using the value of the highlighted field
# (if available). If a sibling content instance has the same permalink then a
# unique one will be generated.
# It applies that to every translated version of the content entry.
def set_slug
  self.translated_in.each do |locale|
    Locomotive::Mounter.with_locale(locale) do
      # first attempt from the label
      if self._slug.blank?
        self._slug = self._label.try(:dup)
      end

      # from the content type itself
      if self._slug.blank?
        self._slug = self.content_type.send(:label_to_slug)
      end

      self._slug.permalink!

      self._slug = self.next_unique_slug if self.slug_already_taken?
    end
  end

  self.fill_with_default_slug
end
```

`self._slug` is a `Hash` when it fails, it succeeds with single locale content entries (when it's a `String`).

Backtrace from wagon.log

```
undefined method `permalink!' for #<Hash:0x007f827917e320>
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/models/content_entry.rb:235:in `block (2 levels) in set_slug'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter.rb:90:in `with_locale'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/models/content_entry.rb:224:in `block in set_slug'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/models/content_entry.rb:223:in `each'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/models/content_entry.rb:223:in `set_slug'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/models/content_type.rb:75:in `block in build_entry'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/models/content_type.rb:60:in `tap'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/models/content_type.rb:60:in `build_entry'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/file_system/content_entries_reader.rb:74:in `add'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/file_system/content_entries_reader.rb:29:in `block (2 levels) in fetch_from_filesystem'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/file_system/content_entries_reader.rb:28:in `each'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/file_system/content_entries_reader.rb:28:in `each_with_index'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/file_system/content_entries_reader.rb:28:in `block in fetch_from_filesystem'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/file_system/content_entries_reader.rb:21:in `each'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/file_system/content_entries_reader.rb:21:in `fetch_from_filesystem'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/file_system/content_entries_reader.rb:13:in `read'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/runner.rb:76:in `block (2 levels) in build_mounting_point'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/runner.rb:73:in `each'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/runner.rb:73:in `block in build_mounting_point'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/runner.rb:70:in `tap'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/runner.rb:70:in `build_mounting_point'
  gems/locomotivecms_mounter-1.0.2/lib/locomotive/mounter/reader/runner.rb:29:in `run!'
  gems/locomotivecms_wagon-1.0.1/lib/locomotive/wagon.rb:154:in `require_mounter'
  gems/locomotivecms_wagon-1.0.1/lib/locomotive/wagon.rb:59:in `push'
  gems/locomotivecms_wagon-1.0.1/lib/locomotive/wagon/cli.rb:172:in `push'
  gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
  gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
  gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
  gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
  gems/locomotivecms_wagon-1.0.1/bin/wagon:9:in `<top (required)>'
  bin/wagon:23:in `load'
  bin/wagon:23:in `<main>'
```

Not sure if it's a mounter or a wagon issue.

content type

``` YAML

---
name: Magazine
description: Articles...
slug: magazine
label_field_name: title
order_by: 512b647bc086453dc300000e
order_direction: desc
fields:
- title:
    label: title
    type: string
    required: true
    localized: true
- author:
    label: author
    type: string
- text:
    label: text
    type: text
    required: true
    localized: true
    text_formatting: html
- icon:
    label: icon
    type: file
    hint: upload in highest resolution possible, will be down scaled and optimized
      automatically
    required: true
- publish_date:
    label: publish_date
    type: date
    required: true
```

content entries

``` YAML

---
- works
    _slug: works
    author: Someone
    text:
      en: ! ""
    publish_date: 04/16/2013
- fails
    _slug:
      en: fails
      it: fails
      fr: fails
      de: fails
    title:
      it: Fail
      fr: Fail
      de: Fail
    author: Someone
    text:
      en: ! ""
      it: ! ""
      fr: ! ""
      de: ! ""
    publish_date: 03.04.2013
```

(both YAML files were created via `wagon pull`)
