### ISSUE TITLE
Create/Manage Additional Items in Left Menu of Back Office

### ISSUE THREAD

**Issue by greyskin** [locomotivecms/wagon#414]
It would be useful if we could create additional items to be displayed in the left menu of the Back Office.

The horizontal tabs created by metafields_schema labels are great, but depending on the requirements of a site, this area can get cluttered, as can the pages accessed via each tab.

I envisage something like the mockup below:

![mockup-sidepanel](https://user-images.githubusercontent.com/17583193/191888791-44e3cc37-7fef-4eea-b9bd-3a3b9abda72b.jpg)

In terms of management, could it not continue to be managed via metafields_schema.yml? Perhaps each label/tab could have a 'group' property (similar to that in content_type fields). Each group would be a separate left menu item.

Example:
```
metafields:

  general_info:
    name:
    legal_name:
    incorporation_year:
    website_build_year:
    history:
    group: organisation_info

  address:
    unit_type:
    street_address: 
    suburb_rd: 
    town_city: 
    postcode:
    display_address:
    po_box:
    box_lobby:
    po_box_town_city:
    po_box_postcode:
    display_po_box:
    group: organisation_info

  phone:
    number_main:
    number_fax:
    number_mobile:
    number_free:
    display_number:
    nav_number:
    group: organisation_info
    
  google:
    analytics_type:
    tags:
    recaptcha_site_key:
    recaptcha_secret:
    map_api_key:
    map_place_id:
    map_zoom: '13'
    map_type: satellite
    map_display: bottom
    group: integrations
```
