### ISSUE TITLE
wagon doesn't deploy seo_title, meta_keywords or meta_description for content_entries

### ISSUE THREAD

**Issue by greyskin** [locomotivecms/wagon#415]
Given the following **/data/development/my-content-type.yml**
```
- My Entry:
    _slug: my-entry
    enabled: true
    name: My Entry
    img: "/samples/_development/content_entries/my-image.jpg"
    seo_title: My Entry
    meta_keywords: test
    meta_description: test
    _id:
    - 123456789123456789123456
    - my-entry
```

...and running
```
wagon deploy staging -r content_entries -f -my-content-type -d -e development
```

results in a successful deploy of the content_entry to the staging platform, except `seo_title`, `meta_keywords` and `meta_description` are ignored.
