### ISSUE TITLE
Wagon pull erases the foreign key of data 

### ISSUE THREAD

**Issue by Sephi-Chan** [locomotivecms/wagon#72]
Hi,

In my site (powered by wagon 1.1.0) I use the following content types:

``` yml

---
name: Photos
slug: photos
label_field_name: title
order_by: created_at
fields:
- title:
    label: title
    type: string
    required: true
- event:
    label: event
    type: belongs_to
    required: true
    class_name: events
    ui_enabled: true
- picture:
    label: picture
    type: file
    required: true


---
name: Events
slug: events
label_field_name: occurred_at
order_by: created_at
fields:
- photos:
    label: photos
    type: has_many
    class_name: photos
    inverse_of: event
    ui_enabled: true
- occurred_at:
    label: occurred_at
    type: date
    required: true
```

In the deployed site, I created some data (an event with many photos) and it works well, but when I use `wagon pull` to fetch those data, the generated file for photos have blank in the `event` attribute, so I have orphans photos.

``` yml
- Foo:
    _slug: foo
    legend: <p>Foo</p>
    picture: /samples/photos/foo.png
    event:   
```

Thanks!
