### ISSUE TITLE
relationships do not properly get pulled into YML data file

### ISSUE THREAD

**Issue by tpreusse** [locomotivecms/wagon#88]
`has_many` seems to get properly saved into the data file

```
- Zürich:
    _slug:
      de: zurich
      en: zurich
      it: zurich
    name:
      en: Zurich
      it: Zurigo
    highlights:
    - grossmunster
    - fraumunster-kirche
    - zurcher-altstadt
    - uetliberg-slash-felsenegg
    events:
    - das-sechselauten-in-zurich-zh
    - das-knabenschiessen-in-zurich
    - streetparade
    - zuri-fascht
```

However the inverse `belongs_to` is empty after a `wagon pull`.

```
- Sechseläuten:
    _slug:
      de: das-sechselauten-in-zurich-zh
      fr: das-sechselauten-in-zurich-zh
    title:
      fr: Sechseläuten
      de: Sechseläuten
      it: Sechseläuten
      en: Sechseläuten
    location:
```

Which then causes the relationship not to work when pushing the data to a different ENV.

Models used when bug occurred

```

---
name: location pages
slug: location_page
label_field_name: name
order_by: created_at
fields:
- name:
    label: name
    type: string
    required: true
    localized: true
- highlights:
    label: highlights
    type: has_many
    class_name: highlight
    inverse_of: location
    ui_enabled: true
- events:
    label: events
    type: has_many
    class_name: events
    inverse_of: location
    ui_enabled: true

---
name: events
slug: events
label_field_name: title
order_by: created_at
group_by: location
fields:
- title:
    label: title
    type: string
    required: true
    localized: true
- location:
    label: location
    type: belongs_to
    required: true
    class_name: location_page
    ui_enabled: true

---
name: highlights
slug: highlight
label_field_name: title
order_by: created_at
group_by: location
fields:
- title:
    label: title
    type: string
    required: true
    localized: true
- location:
    label: location
    type: belongs_to
    required: true
    class_name: location_page
    ui_enabled: true
```
